"""core URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path
from api import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'^api/useraccount/$', views.UserAccount_List),
    path(r'^api/useraccount/([0-9]*)$', views.UserAccount_Detail),
    path(r'^api/userconfig/$', views.UserConfig_List),
    path(r'^api/userconfig/([0-9]*)$', views.UserConfig_Detail),
    path(r'^api/molecule/$', views.Molecule_List),
    path(r'^api/molecule/([0-9]*)$', views.Molecule_Detail),
    path(r'^api/location/$', views.Location_List),
    path(r'^api/location/([0-9]*)$', views.Location_Detail),
    path(r'^api/row/$', views.Row_List),
    path(r'^api/row/([0-9]*)$', views.Row_Detail),
    path(r'^api/rack/$', views.Rack_List),
    path(r'^api/rack/([0-9]*)$', views.Rack_Detail),
    path(r'^api/atom/$', views.Atom_List),
    path(r'^api/atom/([0-9]*)$', views.Atom_Detail),
    path(r'^api/attribute/$', views.Attribute_List),
    path(r'^api/attribute/([0-9]*)$', views.Attribute_Detail),
    path(r'^api/chapter/$', views.Chapter_List),
    path(r'^api/chapter/([0-9]*)$', views.Chapter_Detail),
    path(r'^api/dictionary/$', views.Dictionary_List),
    path(r'^api/dictionary/([0-9]*)$', views.Dictionary_Detail),
    path(r'^api/objecttype/$', views.ObjectType_List),
    path(r'^api/objecttype/([0-9]*)$', views.ObjectType_Detail),
    path(r'^api/object/$', views.Object_List),
    path(r'^api/object/([0-9]*)$', views.Object_Detail),
    path(r'^api/attributemap/$', views.AttributeMap_List),
    path(r'^api/attributemap/([0-9]*)$', views.AttributeMap_Detail),
    path(r'^api/attributevaluestring/$', views.AttributeValueString_List),
    path(r'^api/attributevaluestrin/([0-9]*)$', views.AttributeValueStrin_Detail),
    path(r'^api/attributevalueint/$', views.AttributeValueInt_List),
    path(r'^api/attributevalueint/([0-9]*)$', views.AttributeValueInt_Detail),
    path(r'^api/attributevaluefloat/$', views.AttributeValueFloat_List),
    path(r'^api/attributevaluefloat/([0-9]*)$', views.AttributeValueFloat_Detail),
    path(r'^api/attributevaluedict/$', views.AttributeValueDict_List),
    path(r'^api/attributevaluedict/([0-9]*)$', views.AttributeValueDict_Detail),
    path(r'^api/attributevaluedate/$', views.AttributeValueDate_List),
    path(r'^api/attributevaluedate/([0-9]*)$', views.AttributeValueDate_Detail),
    path(r'^api/ipv4address/$', views.IPv4Address_List),
    path(r'^api/ipv4address/([0-9]*)$', views.IPv4Address_Detail),
    path(r'^api/ipv4vs/$', views.IPv4VS_List),
    path(r'^api/ipv4vs/([0-9]*)$', views.IPv4VS_Detail),
    path(r'^api/ipv4allocation/$', views.IPv4Allocation_List),
    path(r'^api/ipv4allocation/([0-9]*)$', views.IPv4Allocation_Detail),
    path(r'^api/ipv4rspool/$', views.IPv4RSPool_List),
    path(r'^api/ipv4rspool/([0-9]*)$', views.IPv4RSPool_Detail),
    path(r'^api/ipv4rs/$', views.IPv4RS_List),
    path(r'^api/ipv4rs/([0-9]*)$', views.IPv4RS_Detail),
    path(r'^api/ipv4lb/$', views.IPv4LB_List),
    path(r'^api/ipv4lb/([0-9]*)$', views.IPv4LB_Detail),
    path(r'^api/ipv4log/$', views.IPv4Log_List),
    path(r'^api/ipv4log/([0-9]*)$', views.IPv4Log_Detail),
    path(r'^api/ipv4nat/$', views.IPv4NAT_List),
    path(r'^api/ipv4nat/([0-9]*)$', views.IPv4NAT_Detail),
    path(r'^api/ipv4network/$', views.IPv4Network_List),
    path(r'^api/ipv4network/([0-9]*)$', views.IPv4Network_Detail),
    path(r'^api/ipv6address/$', views.IPv6Address_List),
    path(r'^api/ipv6address/([0-9]*)$', views.IPv6Address_Detail),
    path(r'^api/ipv6allocation/$', views.IPv6Allocation_List),
    path(r'^api/ipv6allocation/([0-9]*)$', views.IPv6Allocation_Detail),
    path(r'^api/ipv6log/$', views.IPv6Log_List),
    path(r'^api/ipv6log/([0-9]*)$', views.IPv6Log_Detail),
    path(r'^api/ipv6network/$', views.IPv6Network_List),
    path(r'^api/ipv6network/([0-9]*)$', views.IPv6Network_Detail),
    path(r'^api/config/$', views.Config_List),
    path(r'^api/config/([0-9]*)$', views.Config_Detail),
    path(r'^api/file/$', views.File_List),
    path(r'^api/file/([0-9]*)$', views.File_Detail),
    path(r'^api/filelinkipv4network/$', views.FileLinkIPv4Network_List),
    path(r'^api/filelinkipv4network/([0-9]*)$', views.FileLinkIPv4Network_Detail),
    path(r'^api/filelinkipv4rspool/$', views.FileLinkIPv4RSPool_List),
    path(r'^api/filelinkipv4rspool/([0-9]*)$', views.FileLinkIPv4RSPool_Detail),
    path(r'^api/filelinkipv4vs/$', views.FileLinkIPv4VS_List),
    path(r'^api/filelinkipv4vs/([0-9]*)$', views.FileLinkIPv4VS_Detail),
    path(r'^api/filelinkipv6network/$', views.FileLinkIPv6Network_List),
    path(r'^api/filelinkipv6network/([0-9]*)$', views.FileLinkIPv6Network_Detail),
    path(r'^api/filelinklocation/$', views.FileLinkLocation_List),
    path(r'^api/filelinklocation/([0-9]*)$', views.FileLinkLocation_Detail),
    path(r'^api/filelinkobject/$', views.FileLinkObject_List),
    path(r'^api/filelinkobject/([0-9]*)$', views.FileLinkObject_Detail),
    path(r'^api/filelinkrack/$', views.FileLinkRack_List),
    path(r'^api/filelinkrack/([0-9]*)$', views.FileLinkRack_Detail),
    path(r'^api/filelinkrow/$', views.FileLinkRow_List),
    path(r'^api/filelinkrow/([0-9]*)$', views.FileLinkRow_Detail),
    path(r'^api/filelinkuser/$', views.FileLinkUser_List),
    path(r'^api/filelinkuser/([0-9]*)$', views.FileLinkUser_Detail),
    path(r'^api/mountoperation/$', views.MountOperation_List),
    path(r'^api/mountoperation/([0-9]*)$', views.MountOperation_Detail),
    path(r'^api/objecthistory/$', views.ObjectHistory_List),
    path(r'^api/objecthistory/([0-9]*)$', views.ObjectHistory_Detail),
    path(r'^api/objectlog/$', views.ObjectLog_List),
    path(r'^api/objectlog/([0-9]*)$', views.ObjectLog_Detail),
    path(r'^api/patchcableconnector/$', views.PatchCableConnector_List),
    path(r'^api/patchcableconnector/([0-9]*)$', views.PatchCableConnector_Detail),
    path(r'^api/patchcabletype/$', views.PatchCableType_List),
    path(r'^api/patchcabletype/([0-9]*)$', views.PatchCableType_Detail),
    path(r'^api/patchcableconnectorcompat/$', views.PatchCableConnectorCompat_List),
    path(r'^api/patchcableconnector_detailcompat/([0-9]*)$', views.PatchCableConnector_DetailCompat),
    path(r'^api/patchcableheap/$', views.PatchCableHeap_List),
    path(r'^api/patchcableheap/([0-9]*)$', views.PatchCableHeap_Detail),
    path(r'^api/patchcableheaplog/$', views.PatchCableHeapLog_List),
    path(r'^api/patchcableheaplog/([0-9]*)$', views.PatchCableHeapLog_Detail),
    path(r'^api/plugin/$', views.Plugin_List),
    path(r'^api/plugin/([0-9]*)$', views.Plugin_Detail),
    path(r'^api/portinnerinterface/$', views.PortInnerInterface_List),
    path(r'^api/portinnerinterface/([0-9]*)$', views.PortInnerInterface_Detail),
    path(r'^api/portouterinterface/$', views.PortOuterInterface_List),
    path(r'^api/portouterinterface/([0-9]*)$', views.PortOuterInterface_Detail),
    path(r'^api/patchcableoifcompat/$', views.PatchCableOIFCompat_List),
    path(r'^api/patchcableoifcompat/([0-9]*)$', views.PatchCableOIFCompat_Detail),
    path(r'^api/port/$', views.Port_List),
    path(r'^api/port/([0-9]*)$', views.Port_Detail),
    path(r'^api/vlandomain/$', views.VLANDomain_List),
    path(r'^api/vlandomain/([0-9]*)$', views.VLANDomain_Detail),
    path(r'^api/vlandescription/$', views.VLANDescription_List),
    path(r'^api/vlandescription/([0-9]*)$', views.VLANDescription_Detail),
    path(r'^api/vlanipv4/$', views.VLANIPv4_List),
    path(r'^api/vlanipv4/([0-9]*)$', views.VLANIPv4_Detail),
    path(r'^api/vlanipv6/$', views.VLANIPv6_List),
    path(r'^api/vlanipv6/([0-9]*)$', views.VLANIPv6_Detail),
    path(r'^api/portallowedvlan/$', views.PortAllowedVLAN_List),
    path(r'^api/portallowedvlan/([0-9]*)$', views.PortAllowedVLAN_Detail),
    path(r'^api/portcompat/$', views.PortCompat_List),
    path(r'^api/portcompat/([0-9]*)$', views.PortCompat_Detail),
    path(r'^api/portinterfacecompat/$', views.PortInterfaceCompat_List),
    path(r'^api/portinterfacecompat/([0-9]*)$', views.PortInterfaceCompat_Detail),
    path(r'^api/portlog/$', views.PortLog_List),
    path(r'^api/portlog/([0-9]*)$', views.PortLog_Detail),
    path(r'^api/portvlanmode/$', views.PortVLANMode_List),
    path(r'^api/portvlanmode/([0-9]*)$', views.PortVLANMode_Detail),
    path(r'^api/rackobject/$', views.RackObject_List),
    path(r'^api/rackobject/([0-9]*)$', views.RackObject_Detail),
    path(r'^api/rackspace/$', views.RackSpace_List),
    path(r'^api/rackspace/([0-9]*)$', views.RackSpace_Detail),
    path(r'^api/rackthumbnail/$', views.RackThumbnail_List),
    path(r'^api/rackthumbnail/([0-9]*)$', views.RackThumbnail_Detail),
    path(r'^api/script/$', views.Script_List),
    path(r'^api/script/([0-9]*)$', views.Script_Detail),
    path(r'^api/tag/$', views.Tag_List),
    path(r'^api/tag/([0-9]*)$', views.Tag_Detail),
    path(r'^api/tagfile/$', views.TagFile_List),
    path(r'^api/tagfile/([0-9]*)$', views.TagFile_Detail),
    path(r'^api/tagipv4network/$', views.TagIPv4Network_List),
    path(r'^api/tagipv4network/([0-9]*)$', views.TagIPv4Network_Detail),
    path(r'^api/tagipv4rspool/$', views.TagIPv4RSPool_List),
    path(r'^api/tagipv4rspool/([0-9]*)$', views.TagIPv4RSPool_Detail),
    path(r'^api/tagipv4vs/$', views.TagIPv4VS_List),
    path(r'^api/tagipv4vs/([0-9]*)$', views.TagIPv4VS_Detail),
    path(r'^api/tagipv6network/$', views.TagIPv6Network_List),
    path(r'^api/tagipv6network/([0-9]*)$', views.TagIPv6Network_Detail),
    path(r'^api/taglocation/$', views.TagLocation_List),
    path(r'^api/taglocation/([0-9]*)$', views.TagLocation_Detail),
    path(r'^api/tagobject/$', views.TagObject_List),
    path(r'^api/tagobject/([0-9]*)$', views.TagObject_Detail),
    path(r'^api/tagrack/$', views.TagRack_List),
    path(r'^api/tagrack/([0-9]*)$', views.TagRack_Detail),
    path(r'^api/vlanstrule/$', views.VLANSTRule_List),
    path(r'^api/vlanstrule/([0-9]*)$', views.VLANSTRule_Detail),
    path(r'^api/vlanswitchtemplate/$', views.VLANSwitchTemplate_List),
    path(r'^api/vlanswitchtemplate/([0-9]*)$', views.VLANSwitchTemplate_Detail),
    path(r'^api/vlanswitch/$', views.VLANSwitch_List),
    path(r'^api/vlanswitch/([0-9]*)$', views.VLANSwitch_Detail),
    path(r'^api/vlanvalidid/$', views.VLANValidID_List),
    path(r'^api/vlanvalidid/([0-9]*)$', views.VLANValidID_Detail),
    path(r'^api/vs/$', views.VS_List),
    path(r'^api/vs/([0-9]*)$', views.VS_Detail),
    path(r'^api/vsenabledips/$', views.VSEnabledIPs_List),
    path(r'^api/vsenabledips/([0-9]*)$', views.VSEnabledIPs_Detail),
    path(r'^api/vsenabledports/$', views.VSEnabledPorts_List),
    path(r'^api/vsenabledports/([0-9]*)$', views.VSEnabledPorts_Detail),
    path(r'^api/vsips/$', views.VSIPs_List),
    path(r'^api/vsips/([0-9]*)$', views.VSIPs_Detail),
    path(r'^api/vsports/$', views.VSPorts_List),
    path(r'^api/vsports/([0-9]*)$', views.VSPorts_Detail),
]
